theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1_add:
  - forecolor
  - backcolor
theme_advanced_buttons2_add:
  - emotions
  - iespell
  - media
  - advhr
  - print
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - insertfile
  - insertimage

plugins:
  - table
  - fullscreen
  - emotions
  - advhr
  - iespell
  - media
  - style
  - print